FROM oven/bun:1.3.14 AS bun
FROM node:22-bookworm-slim

COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun
WORKDIR /monorepo

COPY package.json bun.lock tsconfig.base.json tsconfig.package.json tsconfig.json ./
COPY packages ./packages
COPY apps ./apps
RUN bun install --frozen-lockfile
RUN bun run build:packages

WORKDIR /monorepo/apps/web
CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0", "--strictPort"]
